-- `CREATE TABLE` with a qualified name, an `IF NOT EXISTS` guard, and the newer types.
CREATE TABLE IF NOT EXISTS s.t (
  id      INTEGER NOT NULL PRIMARY KEY,
  ts      TIMESTAMP(6) WITH TIME ZONE,
  ts2     TIME WITHOUT TIME ZONE,
  iv      INTERVAL DAY(3) TO SECOND(6),
  parent  INTEGER REFERENCES s.t (id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT fk FOREIGN KEY (id, parent) REFERENCES other.tab (a, b) ON DELETE SET NULL
);
CREATE TEMPORARY TABLE tmp AS SELECT * FROM t;
CREATE GLOBAL TEMPORARY TABLE tmp2 (a INT);

-- Views, indexes, and schemas.
CREATE VIEW v AS SELECT * FROM t;
CREATE OR REPLACE VIEW v (a, b) AS SELECT x, y FROM t WITH CASCADED CHECK OPTION;
CREATE VIEW w AS SELECT * FROM t WITH CHECK OPTION;
CREATE INDEX idx ON t (a);
CREATE UNIQUE INDEX IF NOT EXISTS idx ON s.t (a, b DESC);
CREATE SCHEMA IF NOT EXISTS s;

-- One `ALTER TABLE` action per statement, as the standard has it.
ALTER TABLE t ADD COLUMN c INTEGER NOT NULL DEFAULT 0;
ALTER TABLE t ADD d VARCHAR(10);
ALTER TABLE t DROP COLUMN c CASCADE;
ALTER TABLE t ADD CONSTRAINT u UNIQUE (a, b);
ALTER TABLE t DROP CONSTRAINT u RESTRICT;
ALTER TABLE t ALTER COLUMN a SET DEFAULT 1;
ALTER TABLE t ALTER COLUMN a DROP DEFAULT;
ALTER TABLE t ALTER COLUMN a SET NOT NULL;
ALTER TABLE t ALTER COLUMN a DROP NOT NULL;
ALTER TABLE t ALTER COLUMN a SET DATA TYPE VARCHAR(20);
ALTER TABLE t RENAME TO u;
ALTER TABLE t RENAME COLUMN a TO b;

-- Dropping, in every flavor.
DROP TABLE IF EXISTS s.t CASCADE;
DROP VIEW v;
DROP INDEX idx;
DROP SCHEMA s RESTRICT;
TRUNCATE TABLE s.t;

-- Transaction control.
START TRANSACTION;
BEGIN;
BEGIN WORK;
SAVEPOINT sp;
ROLLBACK TO SAVEPOINT sp;
RELEASE SAVEPOINT sp;
COMMIT WORK;
ROLLBACK;

-- `INSERT` sources: a `VALUES` table, a query, or nothing but defaults.
INSERT INTO t DEFAULT VALUES;
INSERT INTO t (a, b) VALUES (1, DEFAULT), (2, 3);
INSERT INTO s.t SELECT * FROM u ORDER BY a LIMIT 3;
